services:
  # “app” is for general‐purpose CLI container
  app:
    build: .
    volumes:
      - ./:/app
      - ./watched:/watched
      - ./logs:/app/var/log
    entrypoint: []

  # “watcher” is the long-running inotify process
  watcher:
    build: .
    volumes:
      - ./:/app
      - ./watched:/watched
      - ./logs:/app/var/log
    command: ["file:watch"]
